version: "2.2"
services:
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "80:80"
    links:
      - app

  app:
    cpus: 1
    mem_limit: 1g
    build: ruby/ # Go実装の場合は golang/
    container_name: app
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
    init: true

  mysql:
    cpus: 1
    mem_limit: 1g
    image: mysql:8.0.25
    container_name: mysql
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=isuconp"
    volumes:
      - ./etc/mysql/data:/var/lib/mysql
      - ./etc/mysql/sql:/docker-entrypoint-initdb.d
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  memcached:
    image: memcached:1.6.9
